### ISSUE TITLE
Can you release the .config ?

### ISSUE THREAD

**Issue by moul** [jpetazzo/sekexe#5]
I'm trying to add some features on https://github.com/moul/travis-docker/ like `block-device` support

I'm now building a new `uml` binary based on a `make defconfig ARCH=um`, it would be very easier for me to start from your .config file

Thanks!

**Comment by moul** [comment]
Got it using `/proc/config.gz` (https://gist.github.com/moul/6a6e49e52cf9440d5a50)

**Comment by jpetazzo** [comment]
Sorry, saw this a bit late! I don't remember if I had built this myself or if I had found it somewhere. :|

**Comment by moul** [comment]
No problem, I'm now building mine here in Docker: https://github.com/moul/travis-docker/tree/master/uml-builder
